version: '2'

services:
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_USER: mpal
      POSTGRES_PASSWORD: mpal
    volumes_from:
      - data
    ports:
      - 5432:5432
  data:
    image: busybox
    volumes:
      - "/var/lib/postgresql"

  redis:
    image: redis

  mpal:
    depends_on:
      - postgres
      - redis
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app/
    command: foreman start web

  sidekiq:
    depends_on:
      - redis
    build:
      context: .
    volumes:
      - .:/app/
    command: foreman start worker

