config: &config
  adapter: postgresql
  encoding: unicode
  username: mpal
  password: mpal
  pool: 5
  host: localhost

development:
  database: mpal
  <<: *config

test:
  database: mpal_test
  <<: *config
